[package]
name = "podinfo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4.3"
env_logger = "0.9.0"
envconfig = "0.10.0"
serde_json = "1.0.76"
tokio = { version = "1.15.0", features = [ "macros", "rt-multi-thread" ] }
