[package]
name = "podinfo-rs"
version = "0.2.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4.5"
env_logger = "0.9.0"
envconfig = "0.10.0"
serde_json = "1.0.78"
tokio = { version = "1.16.1", features = [ "macros", "rt-multi-thread" ] }
